### ISSUE TITLE
Translatie controller flash messages

### ISSUE THREAD

**Issue by Tjoosten** [Misfits-BE/Kernwapen-Referendum#91]
**TODO:** 

- [ ] Fix unit tests 
- [ ] Implement french translations 
- [ ] Implement english translations.
